define(['knockout','../accUtils','../services/api'],function(ko,accUtils,api){
 function ClaimsViewModel(){const user=api.currentUser(),state=api.context();this.isCustomer=ko.observable(user&&user.role==='POLICYHOLDER');this.policies=ko.observableArray(state.policies||[]);this.policyId=ko.observable(state.selectedPolicyId||(this.policies()[0]&&this.policies()[0].id));this.claimDate=ko.observable(new Date().toISOString().slice(0,10));this.amount=ko.observable();this.reason=ko.observable('');this.claims=ko.observableArray([]);this.claimId=ko.observable();this.settlementStatus=ko.observable('APPROVED');this.settlementAmount=ko.observable();this.message=ko.observable('');this.error=ko.observable(false);this.busy=ko.observable(false);this.money=(v)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
 const run=async(work,msg)=>{this.busy(true);this.message('');try{const d=await work();this.message(msg||'');this.error(false);return d;}catch(e){this.message(e.message);this.error(true);throw e;}finally{this.busy(false);}};
 this.policyId.subscribe(id=>{if(id){api.saveContext({selectedPolicyId:+id});this.load();}});
 this.load=async()=>{if(!this.policyId())return;try{this.claims(await api.request('/claims/policy/'+this.policyId()));}catch(e){this.message(e.message);this.error(true);}};
 this.register=async()=>{try{await run(()=>api.request('/claims',{method:'POST',body:{policyId:+this.policyId(),claimDate:this.claimDate(),claimAmount:+this.amount(),claimReason:this.reason(),assessmentStatus:'PENDING',claimStatus:'REGISTERED'}}),'Claim registered. Our claims team can now assess it.');this.amount('');this.reason('');await this.load();}catch(e){}};
 this.loadPending=async()=>{this.busy(true);try{this.claims(await api.request('/claims/pending'));}catch(e){this.message(e.message);this.error(true);}finally{this.busy(false);}};
 this.decideClaim=async(claim,status)=>{const amountQuery=status==='SETTLED'?'&amount='+encodeURIComponent(claim.claimAmount):'';try{await run(()=>api.request('/claims/'+claim.id+'/settlement?status='+status+amountQuery,{method:'PUT'}),status==='SETTLED'?'Claim approved and settled.':'Claim rejected.');await this.loadPending();}catch(e){}};
 this.settle=async()=>{try{await run(()=>api.request('/claims/'+this.claimId()+'/settlement?status='+encodeURIComponent(this.settlementStatus())+'&amount='+encodeURIComponent(this.settlementAmount()||''),{method:'PUT'}),'Claim settlement decision saved.');await this.load();}catch(e){}};
 this.connected=()=>{accUtils.announce('Claims page loaded.','polite');document.title='Claims - SecureLife';if(this.isCustomer())this.load();else this.loadPending();};}return ClaimsViewModel;
});
