spring.application.name=product-service
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties],optional:file:../../.env[.properties]
server.port=${PRODUCT_SERVICE_PORT:8083}

spring.datasource.url=${PRODUCT_DB_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/product_db}
spring.datasource.username=${PRODUCT_DB_USERNAME:${MYSQL_USER}}
spring.datasource.password=${PRODUCT_DB_PASSWORD:${MYSQL_PASSWORD}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/}
eureka.client.healthcheck.enabled=true
eureka.client.refresh.enable=false
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:false}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
springdoc.swagger-ui.path=/swagger-ui.html
